<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Whoops' => array($vendorDir . '/filp/whoops/src'),
    'Slim' => array($vendorDir . '/slim/slim'),
    'JSMin\\' => array($vendorDir . '/mrclay/jsmin-php/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
);
