<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Respect\\Validation\\' => array($vendorDir . '/respect/validation/library'),
    'NilPortugues\\Sitemap\\' => array($vendorDir . '/sonrisa/sitemap-component/src'),
    'League\\Flysystem\\' => array($vendorDir . '/league/flysystem/src'),
    'Gilbitron\\Util\\' => array($vendorDir . '/gilbitron/php-simplecache/src'),
);
